/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacman.Gui;

import Pacman.Component.Level.*;
import Pacman.Component.Status;
import Pacman.Engine.Drawer;
import Pacman.Engine.Engine;
import Pacman.Component.Settings;
import java.awt.event.KeyEvent;
import javax.swing.Timer;

/**
 *
 * @author GG.Sunshiners
 */
public class Board extends javax.swing.JFrame {
    
    /**
     * engine yang akan menjalankan game ini
     */
    private Engine gameEngine;
    
    /**
     * array bertipe Level yang akan menampung data data level game ini
     */
    private Level level;    
    
    /**
     * atribut ini adalah index untuk level yang sudah dilewati
     */
    private int levelPassed;    
    
    /**
     * atribut untuk menjalankan pengurangan waktu per detik
     */
    private Timer timer;    
    
    /**
     * atribut untuk menyimpan status permainan 
     */
    private Status status;

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        this.gamePanel.setVisible(false);
        this.resultPanel.setVisible(false);
        this.levelPassed=0;
    }
    
     /**
     * method ini berfungsi untuk memasukan drawer kedalam internal frame
     * @param d drawer yang akan dimasukan
     */
    public void setGameFrame(Drawer d)
    {
        this.gameInternalFrame.getContentPane().add(d);
    }
    
    /**
     * method untuk mengubah visibility dari gameFrame
     * @param tf kondisi tampilan gameFrame, true untuk memunculkan, false untuk menghilangkan
     */
    public void setGamePanelVisible(boolean tf)
    {
        this.gamePanel.setVisible(tf);
    }
    
    /**
     * method untuk mengubah visibility dari victoryField
     * @param tf kondisi tampilan gameFrame, true untuk memunculkan, false untuk menghilangkan
     */
    public void setResultPanelVisible(boolean tf)
    {
        this.resultPanel.setVisible(tf);
    }
    
    /**
     * method ini berfungsi untuk mengantur tampilan saat game berakhir dengan kekalahan
     */
    public void gameOver()
    {
        /*
        this.gamePanel.setVisible(false);
        if(this.resultPanel.isVisible()==false)
        {
            this.resultPanel.setVisible(true);
        }
        */
    }
    
    /**
     * method ini akan menampilkan score yang tersisa 
     * @param score score pemain
     */
    public void updateScore(int score)
    {
        this.scoreValueLabel.setText(score+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultPanel = new java.awt.Panel();
        SettingsTitleLabel1 = new javax.swing.JLabel();
        SettingsTitleLabel2 = new javax.swing.JLabel();
        SettingsTitleLabel3 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        gamePanel = new java.awt.Panel();
        scoreLabel = new javax.swing.JLabel();
        scoreValueLabel = new javax.swing.JLabel();
        livesLabel = new javax.swing.JLabel();
        livesValueLabel = new javax.swing.JLabel();
        gameInternalFrame = new javax.swing.JInternalFrame();
        settingsPanel = new javax.swing.JPanel();
        pacmanTitleLabel = new javax.swing.JLabel();
        pacmanSpeedLabel = new javax.swing.JLabel();
        pacmanSpeedTextField = new javax.swing.JTextField();
        pacmanSpeedPercentageLabel = new javax.swing.JLabel();
        pacmanCorneringLabel = new javax.swing.JLabel();
        pacmanCorneringTextField = new javax.swing.JTextField();
        pacmanCorneringPercentageLabel = new javax.swing.JLabel();
        ghostTitleLabel = new javax.swing.JLabel();
        viewDistanceLabel = new javax.swing.JLabel();
        chaseSpeedTextField = new javax.swing.JTextField();
        frightSpeedPercentageLabel = new javax.swing.JLabel();
        frightSpeedLabel = new javax.swing.JLabel();
        frightTextField = new javax.swing.JTextField();
        chaseSpeedPercentageLabel = new javax.swing.JLabel();
        scatterSpeedLabel = new javax.swing.JLabel();
        communicationTextField = new javax.swing.JTextField();
        scatterSpeedPercentageLabel = new javax.swing.JLabel();
        communicationLabel = new javax.swing.JLabel();
        viewDistanceTextField = new javax.swing.JTextField();
        communicationTileLabel = new javax.swing.JLabel();
        chaseSpeedLabel = new javax.swing.JLabel();
        scatterSpeedTextField = new javax.swing.JTextField();
        viewDistanceTileLabel = new javax.swing.JLabel();
        boardTitleLabel = new javax.swing.JLabel();
        foodLabel = new javax.swing.JLabel();
        powerPelletsLabel = new javax.swing.JLabel();
        powerPelletsPointLabel = new javax.swing.JLabel();
        ghostLabel = new javax.swing.JLabel();
        ghostPointLabel = new javax.swing.JLabel();
        minusPerDistanceLabel = new javax.swing.JLabel();
        minusPerDistanceTextField = new javax.swing.JTextField();
        minusPerDistancePointLabel = new javax.swing.JLabel();
        cherryLabel = new javax.swing.JLabel();
        cherryTextField = new javax.swing.JTextField();
        cherryPointLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        ghostTextField = new javax.swing.JTextField();
        minusLabel = new javax.swing.JLabel();
        foodTextField = new javax.swing.JTextField();
        powerPelletsTextField = new javax.swing.JTextField();
        foodPointLabel = new javax.swing.JLabel();
        settingsTitleLabel = new javax.swing.JLabel();
        frightGhostLabel = new javax.swing.JLabel();
        frightGhostValueTextField = new javax.swing.JTextField();
        frightGhostPointLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        resultPanel.setBackground(new java.awt.Color(0, 0, 0));
        resultPanel.setName(""); // NOI18N
        resultPanel.setPreferredSize(new java.awt.Dimension(467, 617));

        SettingsTitleLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SettingsTitleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        SettingsTitleLabel1.setText("Result");

        SettingsTitleLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SettingsTitleLabel2.setForeground(new java.awt.Color(255, 255, 255));
        SettingsTitleLabel2.setText("Insert Here");

        SettingsTitleLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SettingsTitleLabel3.setForeground(new java.awt.Color(255, 255, 255));
        SettingsTitleLabel3.setText("Win!");

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Pacman Win Count =");

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("0");

        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Ghost Win Count =");

        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("0");

        button1.setLabel("Restart");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("Reset Win Count");
        button2.setName(""); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(SettingsTitleLabel2))
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SettingsTitleLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(resultPanelLayout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))))
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(SettingsTitleLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addComponent(SettingsTitleLabel1)
                        .addGap(41, 41, 41)
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SettingsTitleLabel2)
                            .addComponent(SettingsTitleLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );

        gamePanel.setBackground(new java.awt.Color(0, 0, 0));
        gamePanel.setPreferredSize(new java.awt.Dimension(467, 617));
        gamePanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gamePanelKeyPressed(evt);
            }
        });

        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel.setText("Score:");

        scoreValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreValueLabel.setText("0");

        livesLabel.setForeground(new java.awt.Color(255, 255, 255));
        livesLabel.setText("Lives:");

        livesValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        livesValueLabel.setText("0");

        gameInternalFrame.setBackground(new java.awt.Color(0, 0, 0));
        gameInternalFrame.setVisible(true);
        gameInternalFrame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gameInternalFrameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout gameInternalFrameLayout = new javax.swing.GroupLayout(gameInternalFrame.getContentPane());
        gameInternalFrame.getContentPane().setLayout(gameInternalFrameLayout);
        gameInternalFrameLayout.setHorizontalGroup(
            gameInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gameInternalFrameLayout.setVerticalGroup(
            gameInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addComponent(scoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreValueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                        .addComponent(livesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(livesValueLabel)
                        .addGap(25, 25, 25))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addComponent(gameInternalFrame)
                        .addContainerGap())))
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel)
                    .addComponent(scoreValueLabel)
                    .addComponent(livesLabel)
                    .addComponent(livesValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        settingsPanel.setBackground(new java.awt.Color(0, 0, 0));

        pacmanTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pacmanTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        pacmanTitleLabel.setText("Pacman");

        pacmanSpeedLabel.setForeground(new java.awt.Color(255, 255, 255));
        pacmanSpeedLabel.setText("Speed = ");

        pacmanSpeedTextField.setText("100");

        pacmanSpeedPercentageLabel.setForeground(new java.awt.Color(255, 255, 255));
        pacmanSpeedPercentageLabel.setText("%");

        pacmanCorneringLabel.setForeground(new java.awt.Color(255, 255, 255));
        pacmanCorneringLabel.setText("Cornering Rate = ");

        pacmanCorneringTextField.setText("100");

        pacmanCorneringPercentageLabel.setForeground(new java.awt.Color(255, 255, 255));
        pacmanCorneringPercentageLabel.setText("%");

        ghostTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ghostTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        ghostTitleLabel.setText("Ghost");

        viewDistanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewDistanceLabel.setText("View Distance = ");

        chaseSpeedTextField.setText("100");

        frightSpeedPercentageLabel.setForeground(new java.awt.Color(255, 255, 255));
        frightSpeedPercentageLabel.setText("%");

        frightSpeedLabel.setForeground(new java.awt.Color(255, 255, 255));
        frightSpeedLabel.setText("Fright Speed = ");

        frightTextField.setText("100");

        chaseSpeedPercentageLabel.setForeground(new java.awt.Color(255, 255, 255));
        chaseSpeedPercentageLabel.setText("%");

        scatterSpeedLabel.setForeground(new java.awt.Color(255, 255, 255));
        scatterSpeedLabel.setText("Scatter Speed = ");

        communicationTextField.setText("5");

        scatterSpeedPercentageLabel.setForeground(new java.awt.Color(255, 255, 255));
        scatterSpeedPercentageLabel.setText("%");

        communicationLabel.setForeground(new java.awt.Color(255, 255, 255));
        communicationLabel.setText("Circle of Communication Range = ");

        viewDistanceTextField.setText("5");

        communicationTileLabel.setForeground(new java.awt.Color(255, 255, 255));
        communicationTileLabel.setText("Tile");

        chaseSpeedLabel.setForeground(new java.awt.Color(255, 255, 255));
        chaseSpeedLabel.setText("Chase Speed = ");

        scatterSpeedTextField.setText("100");

        viewDistanceTileLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewDistanceTileLabel.setText("Tile");

        boardTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        boardTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        boardTitleLabel.setText("Board Value");

        foodLabel.setForeground(new java.awt.Color(255, 255, 255));
        foodLabel.setText("Food = ");

        powerPelletsLabel.setForeground(new java.awt.Color(255, 255, 255));
        powerPelletsLabel.setText("Power Pellets = ");

        powerPelletsPointLabel.setForeground(new java.awt.Color(255, 255, 255));
        powerPelletsPointLabel.setText("Point");

        ghostLabel.setForeground(new java.awt.Color(255, 255, 255));
        ghostLabel.setText("Ghost = ");

        ghostPointLabel.setForeground(new java.awt.Color(255, 255, 255));
        ghostPointLabel.setText("Point");

        minusPerDistanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        minusPerDistanceLabel.setText("Minus per distance = ");

        minusPerDistanceTextField.setText("50");

        minusPerDistancePointLabel.setForeground(new java.awt.Color(255, 255, 255));
        minusPerDistancePointLabel.setText("Point");

        cherryLabel.setForeground(new java.awt.Color(255, 255, 255));
        cherryLabel.setText("Cherry = ");

        cherryTextField.setText("150");

        cherryPointLabel.setForeground(new java.awt.Color(255, 255, 255));
        cherryPointLabel.setText("Point");

        startButton.setText("Start");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });

        ghostTextField.setText("500");

        minusLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minusLabel.setForeground(new java.awt.Color(255, 255, 255));
        minusLabel.setText("-");

        foodTextField.setText("100");

        powerPelletsTextField.setText("200");

        foodPointLabel.setForeground(new java.awt.Color(255, 255, 255));
        foodPointLabel.setText("Point");

        settingsTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        settingsTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingsTitleLabel.setText("Settings");

        frightGhostLabel.setForeground(new java.awt.Color(255, 255, 255));
        frightGhostLabel.setText("Fright Ghost =");

        frightGhostValueTextField.setText("150");

        frightGhostPointLabel.setForeground(new java.awt.Color(255, 255, 255));
        frightGhostPointLabel.setText("Point");

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pacmanTitleLabel)
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pacmanSpeedLabel)
                                    .addComponent(pacmanCorneringLabel))
                                .addGap(1, 1, 1)
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(settingsPanelLayout.createSequentialGroup()
                                        .addComponent(pacmanCorneringTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pacmanCorneringPercentageLabel))
                                    .addGroup(settingsPanelLayout.createSequentialGroup()
                                        .addComponent(pacmanSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pacmanSpeedPercentageLabel))))
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addComponent(scatterSpeedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scatterSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scatterSpeedPercentageLabel))
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(frightSpeedLabel)
                                    .addComponent(chaseSpeedLabel)
                                    .addComponent(ghostTitleLabel))
                                .addGap(10, 10, 10)
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(frightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chaseSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chaseSpeedPercentageLabel)
                                    .addComponent(frightSpeedPercentageLabel)))
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addComponent(communicationLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(communicationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(communicationTileLabel))
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addComponent(viewDistanceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewDistanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewDistanceTileLabel)))
                        .addGap(19, 19, 19)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                                .addComponent(foodLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(settingsPanelLayout.createSequentialGroup()
                                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(powerPelletsLabel)
                                                    .addComponent(boardTitleLabel))
                                                .addGap(38, 38, 38))
                                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                                .addComponent(ghostLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(minusLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ghostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(foodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(powerPelletsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ghostPointLabel)
                                            .addComponent(powerPelletsPointLabel)
                                            .addComponent(foodPointLabel)))
                                    .addGroup(settingsPanelLayout.createSequentialGroup()
                                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(minusPerDistanceLabel)
                                            .addComponent(cherryLabel)
                                            .addComponent(frightGhostLabel))
                                        .addGap(12, 12, 12)
                                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                                .addComponent(frightGhostValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(frightGhostPointLabel))
                                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                                .addComponent(cherryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cherryPointLabel))
                                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                                .addComponent(minusPerDistanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(minusPerDistancePointLabel)))))
                                .addGap(0, 62, Short.MAX_VALUE))))
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startButton)
                            .addComponent(settingsTitleLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingsTitleLabel)
                .addGap(67, 67, 67)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pacmanTitleLabel)
                    .addComponent(boardTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pacmanSpeedLabel)
                    .addComponent(pacmanSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pacmanSpeedPercentageLabel)
                    .addComponent(foodLabel)
                    .addComponent(foodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodPointLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pacmanCorneringLabel)
                    .addComponent(pacmanCorneringTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pacmanCorneringPercentageLabel)
                    .addComponent(powerPelletsLabel)
                    .addComponent(powerPelletsPointLabel)
                    .addComponent(powerPelletsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ghostTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chaseSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chaseSpeedLabel)
                            .addComponent(chaseSpeedPercentageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frightSpeedLabel)
                            .addComponent(frightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frightSpeedPercentageLabel))
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(viewDistanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewDistanceTileLabel)))
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(settingsPanelLayout.createSequentialGroup()
                                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(scatterSpeedLabel)
                                            .addComponent(scatterSpeedPercentageLabel)
                                            .addComponent(scatterSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, settingsPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(frightGhostLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)))
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(communicationLabel)
                                    .addComponent(communicationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(communicationTileLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewDistanceLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addComponent(startButton)
                        .addGap(60, 60, 60))
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ghostLabel)
                            .addComponent(ghostPointLabel)
                            .addComponent(ghostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minusPerDistanceLabel)
                            .addComponent(minusPerDistanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minusPerDistancePointLabel))
                        .addGap(9, 9, 9)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cherryLabel)
                            .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cherryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cherryPointLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frightGhostValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frightGhostPointLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(resultPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(settingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(resultPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 637, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(settingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        this.settingsPanel.setVisible(false);
        this.gamePanel.setVisible(true);
        int pacmanSpeed=Integer.parseInt(this.pacmanSpeedTextField.getText());
        int corneringRate=Integer.parseInt(this.pacmanCorneringTextField.getText());
        int chaseSpeed=Integer.parseInt(this.chaseSpeedTextField.getText());
        int frightSpeed=Integer.parseInt(this.frightTextField.getText());
        int scatterSpeed=Integer.parseInt(this.scatterSpeedTextField.getText());
        int coc=Integer.parseInt(this.communicationTextField.getText());
        int viewDistance=Integer.parseInt(this.viewDistanceTextField.getText());
        int foodValue=Integer.parseInt(this.foodTextField.getText());
        int powerPelletValue=Integer.parseInt(this.powerPelletsTextField.getText());
        int ghostValue=Integer.parseInt(this.ghostTextField.getText());
        int minusPerDistance=Integer.parseInt(this.minusPerDistanceTextField.getText());
        int cherryValue=Integer.parseInt(this.cherryTextField.getText());
        int frightGhostValue=Integer.parseInt(this.frightGhostValueTextField.getText());
        Settings setting=new Settings(pacmanSpeed, corneringRate, chaseSpeed, frightSpeed, scatterSpeed, coc, viewDistance, foodValue, powerPelletValue, ghostValue, minusPerDistance, cherryValue, frightGhostValue);
        level=new Level(setting);
        if(gameEngine==null){
            gameEngine= new Engine(level, setting, this);
        } else {
            gameEngine.updateNewEngine(level, setting);
        }
        this.gamePanel.setFocusable(true);
    }//GEN-LAST:event_startButtonMouseClicked

    private void gameInternalFrameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gameInternalFrameKeyPressed
        
    }//GEN-LAST:event_gameInternalFrameKeyPressed

    private void gamePanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gamePanelKeyPressed
        int arrowKey = evt.getKeyCode();
        String direction;
        if (arrowKey == KeyEvent.VK_LEFT) {
            gameEngine.runMovingCondition("Left","Pacman");
        }
        else if (arrowKey == KeyEvent.VK_UP) {
            gameEngine.runMovingCondition("Up","Pacman");
        }
        else if (arrowKey == KeyEvent.VK_RIGHT) {
            gameEngine.runMovingCondition("Right","Pacman");
        }
        else if (arrowKey == KeyEvent.VK_DOWN) {
            gameEngine.runMovingCondition("Down","Pacman");
        }
    }//GEN-LAST:event_gamePanelKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SettingsTitleLabel1;
    private javax.swing.JLabel SettingsTitleLabel2;
    private javax.swing.JLabel SettingsTitleLabel3;
    private javax.swing.JLabel boardTitleLabel;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel chaseSpeedLabel;
    private javax.swing.JLabel chaseSpeedPercentageLabel;
    private javax.swing.JTextField chaseSpeedTextField;
    private javax.swing.JLabel cherryLabel;
    private javax.swing.JLabel cherryPointLabel;
    private javax.swing.JTextField cherryTextField;
    private javax.swing.JLabel communicationLabel;
    private javax.swing.JTextField communicationTextField;
    private javax.swing.JLabel communicationTileLabel;
    private javax.swing.JLabel foodLabel;
    private javax.swing.JLabel foodPointLabel;
    private javax.swing.JTextField foodTextField;
    private javax.swing.JLabel frightGhostLabel;
    private javax.swing.JLabel frightGhostPointLabel;
    private javax.swing.JTextField frightGhostValueTextField;
    private javax.swing.JLabel frightSpeedLabel;
    private javax.swing.JLabel frightSpeedPercentageLabel;
    private javax.swing.JTextField frightTextField;
    private javax.swing.JInternalFrame gameInternalFrame;
    private java.awt.Panel gamePanel;
    private javax.swing.JLabel ghostLabel;
    private javax.swing.JLabel ghostPointLabel;
    private javax.swing.JTextField ghostTextField;
    private javax.swing.JLabel ghostTitleLabel;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JLabel livesLabel;
    private javax.swing.JLabel livesValueLabel;
    private javax.swing.JLabel minusLabel;
    private javax.swing.JLabel minusPerDistanceLabel;
    private javax.swing.JLabel minusPerDistancePointLabel;
    private javax.swing.JTextField minusPerDistanceTextField;
    private javax.swing.JLabel pacmanCorneringLabel;
    private javax.swing.JLabel pacmanCorneringPercentageLabel;
    private javax.swing.JTextField pacmanCorneringTextField;
    private javax.swing.JLabel pacmanSpeedLabel;
    private javax.swing.JLabel pacmanSpeedPercentageLabel;
    private javax.swing.JTextField pacmanSpeedTextField;
    private javax.swing.JLabel pacmanTitleLabel;
    private javax.swing.JLabel powerPelletsLabel;
    private javax.swing.JLabel powerPelletsPointLabel;
    private javax.swing.JTextField powerPelletsTextField;
    private java.awt.Panel resultPanel;
    private javax.swing.JLabel scatterSpeedLabel;
    private javax.swing.JLabel scatterSpeedPercentageLabel;
    private javax.swing.JTextField scatterSpeedTextField;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreValueLabel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JLabel settingsTitleLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel viewDistanceLabel;
    private javax.swing.JTextField viewDistanceTextField;
    private javax.swing.JLabel viewDistanceTileLabel;
    // End of variables declaration//GEN-END:variables
}
